apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-kustomize-repo
  annotations:
    tekton.dev/displayName: "Update Kustomize Git Repository"
spec:
  params:
  - name: gitRepositoryUrl
    description: URL of the Git repository to update
    type: string
  - name: gitRepositoryRevision
    description: Branch or Tag to push the update to
    type: string
    default: master
  - name: gitPath
    description: Path in the repository to work in.
    type: string
    default: "."
  - name: fileName
    description: Name of the file to be updated
    type: string
    default: deployment-patches.yaml
  - name: image
    description: The image to be written into the YAML
    type: string
  - name: imageTag
    description: The image tag to be written into the YAML
    type: string
  - name: verbose
    description: Log the commands used during execution
    type: string
    default: "true"

  steps:
  - name: git-checkout
    image: alpine/git:v2.26.2
    workingDir: $(workspaces.repository.path)
    script: |
      #!/usr/bin/env sh

      if [[ "$(params.verbose)" == "true" ]] ; then
        set -x
        echo "**** Cloning $(params.gitRepositoryUrl) into $(pwd)"
      fi

      git clone "$(params.gitRepositoryUrl)" $(pwd)
      git checkout "$(params.gitRepositoryRevision)"

  - name: update-yaml
    image: quay.io/dsanchor/ubi8-git:0.0.2
    workingDir: $(workspaces.repository.path)
    script: |
      #!/usr/bin/env sh
      set -e

      if [[ "$(params.verbose)" == "true" ]] ; then
        echo "**** Updating $(params.fileName) image to $(params.image):$(params.imageTag)"
      fi

      IMAGE_TAG = $(params.imageTag)

      chmod 707 ./$(params.gitPath)/$(params.fileName)

      cat ./deployment_patches.yaml_ |  envsubst > ./deployment_patches.yaml

  - name: commit-push-changes
    image: alpine/git:v2.26.2
    workingDir: $(workspaces.repository.path)
    script: |
      #!/usr/bin/env sh

      git config --global user.email "tekton@tekton.dev"
      git config --global user.name "OpenShift Pipeline"

      git add *
      git commit --allow-empty -m "[OpenShift Pipeline] Updating $(params.fileName) image to $(params.image):$(params.imageTag)"
      git push origin "$(params.gitRepositoryRevision)" -v

  workspaces:
    - name: repository
    