apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ci-pipeline-template
  namespace: cop-pipeline
spec:
  params:
    - name: git-repo-url
    - name: git-revision
    - name: short-commit-id
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: ci-pipeline-
      spec:
        params:
          - name: git-source-url
            value: $(tt.params.git-repo-url)
          - name: git-source-revision
            value: $(tt.params.git-revision)
          - name: short-commit-id
            value: $(tt.params.short-commit-id)
          - name: SONAR_URL
            value: 'http://sonarqube-cicd-tools.apps.xxxxx.xxxx.dev.xxx.ca'
          - name: SONAR_AUTH_TOKEN
            value: cb98fc7b68ea37feb56d151e10b87d6dc596f4b2
          - name: LOCAL_SCAN_PATH
            value: ./
          - name: LOCAL_IMAGE_SCAN_PATH
            value: ./
          - name: REMOTE_IMAGE_URL
            value: >-
              artifactory.XXXX.corp.XXX.ca:5073/ccop-dev/quarkus-ref-image-dev:$(tt.params.short-commit-id)
          - name: SEVERITY_LEVELS
            value: LOW
          - name: KUSTOMIZE_GIT_URL
            value: 'https://gitlab.XXX.corp.XXX.ca/AI/aiocp/tekton-pipeline.git'
          - name: KUSTOMIZE_GIT_CONTEXT_DIR
            value: k8s/overlays/dev
        pipelineRef:
          name: ci-pipeline
        workspaces:
          - name: app-source
            persistentVolumeClaim:
              claimName: source-repo-pvc
          - name: maven-settings
            persistentVolumeClaim:
              claimName: maven-settings-pvc
          - name: shared-image-repo
            persistentVolumeClaim:
              claimName: source-repo-pvc
          - emptyDir: {}
            name: kustomize-repo
